new 3.0 things
Artesians/TCL pull request #1347
Opened 2022-08-24 19:11 UTC by paichlear

2022-09-04 09:35 UTC, ItzSomebody requested changes

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/automatons/ruin-drake-skywatch.md
> +Unknown.
66%: common orb
33%: common orb
death: 2 common particles

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/bosses/overworld-bosses/jadeplume-terroshroom.md
> +Unknown.
66%: dendro orb
33%: dendro orb
death: dendro orb + dendro particle

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/bosses/overworld-bosses/regisvines/regisvines.md
> +| Death | 1 Orb | Own Element |
1 Orb, 1 Orb, 1 Orb, 1Orb

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-axe-vanguard.md
> +Unknown.
60%: common particle
death: common particle

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-crossbow.md
> +Unknown.
60%: common particle
death: common particle

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-crossbow.md
> +## Stat Block
60: 10630.731491043
65: 13976.21506251162
70: 17582.516413765494
75: 22000.76357410103
80: 28363.94175975211
85: 36237.78547225706
90: 44520.347078810446
95: 54514.39322714042
100: 66552.02486602496

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-daythunder.md
> +## Energy Drops
75%: Electro particle
50%: Electro Particle
25%: Electro Particle
death: 2x Electro Particles

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-daythunder.md
> +## Stat Block
60: 35435.76997828111
65: 46587.38136123866
70: 58608.38530278951
75: 73335.87514793873
80: 94546.46810737252
85: 120792.61258730292
90: 148401.14998362958
95: 181714.6355855316
100: 221840.07250379026

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-desert-clearwater.md
> +Unknown.
75%, 50%, 25%: Hydro particle
death: 2x Hydro particles

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-desert-clearwater.md
> +## Stat Block
60: 31892.194473129
65: 41928.64518753486
70: 52747.54924129648
75: 66002.29072230309
80: 85091.82527925633
85: 108713.35641677119
90: 133561.04123643134
95: 163543.17968142126
100: 199656.0745980749

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-linebreaker.md
> +Unknown.
60% and death: common particle

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-ravenbeak-halberdier.md
> +Unknown.
60% and death: common particle

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-ravenbeak-halberdier.md
> +## Stat Block
60: 10630.731491043
65: 13976.21506251162
70: 17582.516413765494
75: 22000.76357410103
80: 28363.94175975211
85: 36237.78547225706
90: 44520.347078810446
95: 54514.39322714042
100: 66552.02486602496

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-sunfrost.md
> +Unknown.
75%, 50%, 25%: cryo particle
death: 2x cryo particle

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-sunfrost.md
> +## Stat Block
60: 31892.194473129
65: 41928.64518753486
70: 52747.54924129648
75: 66002.29072230309
80: 85091.82527925633
85: 108713.35641677119
90: 133561.04123643134
95: 163543.17968142126
100: 199656.0745980749

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/humans/eremites/eremite-sword-dancer.md
> +Unknown.
60% and death: common particle

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/mystical-beasts/fungi.md
> +Unknown.
death: common particle

2022-09-04 09:35 UTC, ItzSomebody commented on enemy-data/mystical-beasts/shrooms.md
> +Unknown.
60% and death: own element particle

2022-09-06 00:16 UTC, ItzSomebody approved these changes

2022-09-10 20:42 UTC, ReensW approved these changes

2022-09-10 20:43 UTC, merged