More plunge
Artesians/TCL pull request #675
Opened 2021-10-08 20:07 UTC by itskhoi

2021-10-08 22:06 UTC, NoelleSimp requested changes

2021-10-08 22:06 UTC, NoelleSimp commented on mechanics/combat/tech/plunge-tech.md
> -# Stepstool
Why are we deleting these?

2021-10-08 22:06 UTC, NoelleSimp commented on mechanics/combat/tech/plunge-tech.md
>  {% page-ref page="../../../evidence/mechanics/combat/tech/Plunge.md" %}
Not part of your change but would be nice in this one, change "Plunge" to "plunge".

2021-10-16 22:51 UTC, itskhoi commented
closing due to conflict

2021-10-16 22:51 UTC, closed without merging